name: Build, Push, and Deploy Next.js Docker Image

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/nextjs-app:latest --push .

  deploy:
    needs: [build-push]
    runs-on: raspberrypi
    env:
      PROJECT_NAME: "nextjs-app"
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker Image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest

      - name: Stop Old Container
        run: sudo docker stop ${{ env.PROJECT_NAME }} || true

      - name: Remove Old Container
        run: sudo docker rm ${{ env.PROJECT_NAME }} || true

      - name: Create Network
        run: sudo docker network create my-network || true

      - name: Run New Container
        run: sudo docker run -d --name ${{ env.PROJECT_NAME }} --network my-network -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/${{ env.PROJECT_NAME }}:latest

      - name: Remove Old Images
        run: sudo docker image prune -a -f || true